# Generated by Django 5.1 on 2024-08-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Location',
            new_name='location',
        ),
    ]
